### ISSUE TITLE
The google drive link of the dataset has expired

### ISSUE THREAD

**Issue by LLeavesG** [natanielruiz/disrupting-deepfakes#3]
the google drive which store the third-party public pre-processed (cropped faces) version of the CelebA dataset has expired，I cannot open the https://drive.google.com/open?id=1MijMc6QnjrNFopT1G43WQFeei9ddcaza,

**Comment by LLeavesG** [comment]
I actually found the dataset on the CelebA website, but when I try to run GANimation, it prompts
Training images:  202499
Testing images:  100
Model running on cuda:0
image 0 AU 0
Traceback (most recent call last):
  File "main.py", line 60, in <module>
    main(config)
  File "main.py", line 32, in main
    solver.animation()
  File "E:\disrupting-deepfakes-master\ganimation\solver.py", line 407, in animation
    resulting_image_noattack = self.imFromAttReg(
  File "E:\disrupting-deepfakes-master\ganimation\utils.py", line 85, in imFromAttReg
    return (1-att)*reg + att*x_real
RuntimeError: The size of tensor a (176) must match the size of tensor b (178) at non-singleton dimension 3
So I have to suspect that there is something wrong with the dataset I found, can you help me?

**Comment by LLeavesG** [comment]
Fine , I just resize the datasets (https://mmlab.ie.cuhk.edu.hk/projects/CelebA.html) from 178x215 to  176x212 that it can be worked
